@url = http://localhost:30000/api
# @url = http://60.205.247.170:30000/api
@json = Content-Type: application/json
@json2 = Content-Type: application/x-www-form-urlencoded

###
get {{url}}

### 所有用户
get {{url}}/allUsers


### 注册
post {{url}}/register
{{json}}

{
    "studentId": "201805130146",
    "realName": "亓龙雨",
    "password": "password123456",
    "invitationCode": "abc",
    "email": "qilongyu@126.com",
    "emailCode": "398989"
}

### 登录
post {{url}}/login
{{json}}

{
    "studentId": "201805130146",
    "password": "password123456"
}

### 个人信息
get {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNzA2MjI4MzE3NmQ3NzJmMGRjZmM3MiIsImlhdCI6MTYwMTIwNDQxNn0.45qnw9RpNzPvkMW9BM3jbkJKJEf7POeo7jjWMFogZqA

### 所有邮箱验证码
get {{url}}/allEmailCode

### 发送邮箱验证码
post {{url}}/sendEmailCode
{{json}}

{
    "email": "qilongyu@126.com"
}

### 邀请码生成
post {{url}}/createInvitationCode
{{json}}

{
    "code": "abccc",
    "total": 100
}

### 创建帖子
post {{url}}/createPost
{{json}}

{
    "postType": 1,
    "creatorId": "201805130163",
    "title": "第3篇帖子的标题",
    "content": "这里是第3篇帖子的内容嗷嗷嗷嗷contentcontentcontentcontentcontentcontentcontentcontentcontentcontentcontentcontentcontentcontentcontentcontentcontentcontentcontentcontentcontentcontentcontentcontentcontent"
}

### 回复帖子
post {{url}}/addPostContent
{{json}}

{
    "post_id": 3,
    "reply_id": "201805130163",
    "reply_content": "抢沙发"
}